package com.qa.exerciseapp.exceptions;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import static org.junit.Assert.*;

public class ExerciseNotFoundExceptionTest {

    @Before
    public void setUp() throws Exception {
    }

    @After
    public void tearDown() throws Exception {
    }

    @Test
    public void getMessage() {
    }

    @Test
    public void getLocalizedMessage() {
    }

    @Test
    public void getCause() {
    }

    @Test
    public void initCause() {
    }

    @Test
    public void testToString() {
    }

    @Test
    public void printStackTrace() {
    }

    @Test
    public void testPrintStackTrace() {
    }

    @Test
    public void testPrintStackTrace1() {
    }

    @Test
    public void fillInStackTrace() {
    }

    @Test
    public void getStackTrace() {
    }

    @Test
    public void setStackTrace() {
    }

    @Test
    public void getStackTraceDepth() {
    }

    @Test
    public void getStackTraceElement() {
    }

    @Test
    public void addSuppressed() {
    }

    @Test
    public void getSuppressed() {
    }
}